version: '3.7'

services:
  api-nginx:
    image: nginx:stable-alpine
    container_name: api-nginx
    ports:
     - "7991:80"
    volumes:
      - ./${PROJECT_FOLDER}:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.frontend.rule=Host:api-contract.local.moratelindo.co.id
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public
  api-php:
    build:
      context: .
      dockerfile: ./Image/Dockerfile
    container_name: api-php
    volumes:
      - ./${PROJECT_FOLDER}:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - traefik-public
networks:
  traefik-public: 
    external: true
